# Generated by Django 3.2.9 on 2021-12-04 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kitchens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='media/default.jpg', upload_to=kitchens.models.upload_to)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to='branches.branches')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
