# Generated by Django 3.2.9 on 2021-12-05 12:31

from django.db import migrations, models
import kitchens.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchens',
            name='label',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitchens',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=kitchens.models.upload_to),
        ),
    ]
