# Generated by Django 3.2.9 on 2021-12-11 01:32

from django.db import migrations, models
import kitchens.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0003_auto_20211210_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=kitchens.models.upload_to),
        ),
    ]
