# Generated by Django 3.2.9 on 2021-12-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0004_alter_kitchens_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
