# Generated by Django 3.2.9 on 2021-12-11 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchens', '0005_alter_kitchens_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchens', to=settings.AUTH_USER_MODEL),
        ),
    ]
