# Generated by Django 3.2.9 on 2021-12-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0006_alter_kitchens_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
