# Generated by Django 3.2.9 on 2021-12-13 21:01

from django.db import migrations, models
import kitchens.models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0008_alter_kitchens_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchens',
            name='image',
            field=models.FileField(blank=True, default='media/default.jpg', upload_to=kitchens.models.upload_to),
        ),
    ]
