# Generated by Django 3.2.9 on 2021-12-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=255)),
                ('UF', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=11)),
            ],
        ),
    ]
