# Generated by Django 3.2.9 on 2021-11-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('kicthen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='kitchens.kitchens')),
            ],
        ),
    ]
