# Generated by Django 3.2.9 on 2021-12-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='kicthen',
            new_name='kitchen',
        ),
    ]
